### ISSUE TITLE
Incorrect constraints on Bookmark cell

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1081]
The text will be off-centered when searching something that doesn't match anything in your bookmarks, then cancelling the search

**Comment by rizwankce** [comment]
I did spend some time with this bug. It seems not the problem with the constraints or auto layout.

We use `AttributedStringView` for the text view in bookmark and during `layoutSubviews` we check for whether details text present or not and based on that center the text view. Guess the problem here is `layoutSubviews` not called when performing updates to collection view during out search.

https://github.com/rnystrom/GitHawk/blob/16c444331297ef4e04338bba451a67c9af315ef9/Classes/Bookmark%20v2/BookmarkCell.swift#L52-L73
