### ISSUE TITLE
Time ago not updated on refresh 

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#126]
See last row
![img_1154](https://user-images.githubusercontent.com/4190298/28133275-c196e456-673f-11e7-97f4-d2c7dc4dcdcd.PNG)

**Comment by rnystrom** [comment]
Ah, that's b/c the cell isn't being reloaded. I'll have to think about this.

**Comment by rnystrom** [comment]
I think calling `reloadData` on reload will fix this, even tho its discouraged by IGListKit

**Comment by Sherlouk** [comment]
Is there any form of reactive we could be using to update a single label every minute rather than the entire cell?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Sherlouk hmm probably. We could honestly just have a 60s "forever" timer that just calls `reloadData`?

**Comment by Sherlouk** [comment]
Hmm I just don't know how happy I am with the idea of reloading entire collection views every minute just to increase a timer! Especially with paging, there could be 100s of entries that will all be updated!

I don't see this as a particularly "uncommon" issue, be interested to see if there's something IGLK could do internally to make this a tad smoother

**Comment by rnystrom** [comment]
Actually reload data is pretty cheap since it only has to configure stuff that’s on screen. The only iffy part is rebuilding the layout, which the expensive bits (text size) are already cached. I’m gonna try this out actually and see what it’s like. 

Agree tho about IGLK. I should come up with a way to do this that is framework-friendly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Linking this to #218 also

**Comment by rnystrom** [comment]
Closing that one out so we're tracking stuff in one place

**Comment by BasThomas** [comment]
Think this was fixed, right @rnystrom?
