### ISSUE TITLE
Mark all as read shortly enabled during refresh

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1344]
From https://github.com/rnystrom/GitHawk/issues/1295#issuecomment-353068818

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1514903367)
Device: iPhone X (iOS 11.2.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Played w/ this last week. Seems like no matter what, if you assign a new `UIBarButtonItem`, even if its initially `isEnabled = false`, it'll flicker. Seems like we need to track what the bar button item actually is, and not replace it if its the mark-all button.

I think if we just keep a ref to the button around instead of rebuilding it every time that'll do it. Wanna take this on @BasThomas?
