### ISSUE TITLE
Missing NSPhotoLibraryAddUsageDescription

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1431]
#### in __TCCAccessRequest_block_invoke_2.85

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/githawk/ios/apps/com.whoisryannystrom.freetime/issues/5a5e82868cb3c2fa63f95a9f?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/githawk/ios/apps/com.whoisryannystrom.freetime/issues/5a5e82868cb3c2fa63f95a9f?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by rnystrom** [comment]
Trying to access user data w/out permissions. Maybe after denying photo access?

**Comment by ajfigueroa** [comment]
@rnystrom I'm unable to access that Fabric link but I was able to reproduce a TCC crash that is likely the same issue.

In iOS 11, there is a new permission for adding photos (write access) to a User's Photo library. The crash is occurring because GitHawk to missing the Info.plist entry for `NSPhotoLibraryAddUsageDescription`. More info [here](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW73)

Steps to Reproduce (iOS 11)
1. Find a PR or Issue that has an image in the body or one of the comments. Ex. https://github.com/rnystrom/GitHawk/pull/481
2. Tap on the image
3. Tap the Share button in the top right corner
4. Tap "Save Image"
5. Observe the app crashes with the following log:
```
This app has crashed because it attempted to access privacy-sensitive
data without a usage description.  The app's Info.plist must contain an
NSPhotoLibraryAddUsageDescription key with a string value explaining 
to the user how the app uses this data.
```

I hope this helps!

**Comment by Sherlouk** [comment]
Public Link: http://crashes.to/s/ff1e99fe37d

**Comment by ajfigueroa** [comment]
Yeah, that crash looks exactly the same as one I've seen at work.
There is no useful information in it unfortunately. I'm pretty confident the reproducible steps I've listed above is the cause 👍
