### ISSUE TITLE
Bring back multiple accounts?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#204]
I keep flip flopping on this. Personally I'd love to have this to swap between test accounts while deving. Do ppl use other accounts often? Bots? I know org support is missing, maybe that'd be useful along with multiple accounts?

I'd have to change the flow to use a personal auth token instead of login, since web flow is limited to current safari session (tho I think we can nil session in iOS 11?).

Thoughts?

**Comment by Sherlouk** [comment]
So I have a work account and a public account, which would be my reason for wanting this - Having “different profiles” would be helpful in order to switch over at end of the day to public profile and see my projects and not be distracted by work and vice versa

probably super out of scope but wonder how difficult it would be to add Bitbucket support and similar? (Org GitHub is also a good one)

**Comment by Sherlouk** [comment]
@rnystrom Is this done now?

**Comment by BasThomas** [comment]
Think so, works with a personal access token.
