### ISSUE TITLE
Changes/Fixes to Search

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#276]
Listing generated off the back of #200, opening separate issue for better tracking

- [ ] ~~Rename the "Search" tab to "Repos" (maybe "Repositories")~~
- [ ] ~~Default load your repositories on the repo tab (could take advantage of init state here)~~
- [x] Put the search bar in the nav view
- [ ] ~~Search as you type (instead of waiting for enter)~~
- [ ] ~~Auto** load next page as you scroll down search results~~
- [ ] ~~Merge SearchLoadMoreCell and IssueNeckLoadCell into one~~
- [x] Redesign repo cells
  - Remove "updated" date, I don't think this is valuable info in a search result
  - Balance colors
- [x] Fix bug showing empty state while loading issues
- [x] Clean up empty state design (no black)
- [x] Clean up Issue/PR cell design to match notifications (bold, spacing)
- [x] Bug tapping issue presents VC, can't go back (both on new repo and old one)
- [x] iPad shows 2 search tabs?
- [x] Cells need highlight state
- [x] Cells need selection/deselection states
- [x] Better handle error states

**Comment by rnystrom** [comment]
Fixed a lot of stuff up. I'm on the fence about calling this tab "Repos" now since I'd like to eventually add a profile tab that would contain your own repos. Plus, the GQL API also lets you search for users and issues. I'm thinking about using the `UISearchBar` scopes API to add a seg control to search for other stuff.

Problem is, the search tab init null state is _really boring_. Some options:

- Still default to your own repos. Maybe a little confusing, but at least should be frequently used?
- Show some cutesy graphic. Useless but at least fill the void.
- If opening the tab and search is empty, make the search bar first responder

Any thoughts or other ideas?

**Comment by BasThomas** [comment]
Those or maybe get some trending repos?

**Comment by Sherlouk** [comment]
Already looked into Trending, there's no way to sort on "Stars Today" which is what that's based 😢

**Comment by Sherlouk** [comment]
> Still default to your own repos

I think we should hold off on this until we have a "Me" tab

> make the search bar first responder

Personally not a fan of apps that do this, if I accidentally tap on it then suddenly a keyboard is in the way and covering the navigation

> Show some cutesy graphic

I think this should be it - Slightly faded out search icon in the middle with a quick summary underneath
