### ISSUE TITLE
Document Apollo install steps

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#282]
Just set up fresh, and noticed we haven't documented the steps to install the Apollo node package. Then it gave an error the Apollo framework and latest node version are out of sync - we might want to update the framework also?

**Comment by rnystrom** [comment]
Hmm good point. Ya I updated apollo once and it all went to hell. Pinned to a specific version.

**Comment by Sherlouk** [comment]
`npm install -g apollo-codegen@10.0`

**Comment by Sherlouk** [comment]
Gonna close this since we have NPM now and the contributing guide also references this.

It's also worth noting that when we upgrade Apollo, it has automatic version syncing, meaning it'll automatically ensure you have the correct version installed before building - So this won't be an issue any further
