### ISSUE TITLE
Convert HTML entities when using in NSAttibutedString

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#307]
Version 1.10.0 (1775)
Device: iPhone 7 Plus (iOS 10.3.3) 

E.g. these emoji

https://raw.githubusercontent.com/Instagram/IGListKit/master/README.md

**Comment by weyert** [comment]
I will have a look into this issue  👍

**Comment by rnystrom** [comment]
Looks like this would be easiest

https://github.com/mwaterfall/MWFeedParser/blob/master/Classes/NSString+HTML.m

**Comment by weyert** [comment]
Yes, I have found something similar through a Pod for Swift (HTMLString) only I am having the issue at the moment that the emoji character are positioned wrongly. Probably because the line height changes when the emoji are added. Still looking into it. Might take a bit longer. Having a dooming deadlines at work.

**Comment by weyert** [comment]
I have added a pr which fixes this ticket. The issue with the emoji's being wrongly positioned was because the table row had a hard-code height. 

Currently, I am iterating to everything and reduce into the max row height and use that. @rnystrom Any better way?
