### ISSUE TITLE
Version number script blocking Testflight submission

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#456]
> ERROR ITMS-90188: "Invalid Pre-Release Build. The CFBundleVersion key in the app’s Info.plist file contains a build number (1) that’s lower than the latest build number (1941) that’s been submitted for the app version '1.11.0'."

I think this was discussed in #386, but using `fastlane beta` does not work now that the build # doesn't change.

@Sherlouk is there something missing for the TF config? Is the script working?

**Comment by rnystrom** [comment]
Manually editing the build # now to get a TF build out, but hoping we can fix this ASAP

**Comment by Sherlouk** [comment]
Two issues here: 1. Because we've already submitted something to version `1.11.0` we can't submit a build number lower (so it'll only work if we increment the version)

2. Looks like it's not working for the binary output of the beta job, I'll double check all my hooks ASAP today

**Comment by Sherlouk** [comment]
Proving a bit difficult to test because I can't generate IPAs using fastlane (amateur dev I know). One possible solution is to just override the main Info.plist as a pre-step, it does mean we'll still get conflicts but it'll only be when we go for releases which may not be as bad?

```
if [ -f "${BUILT_PRODUCTS_DIR}/${WRAPPER_NAME}.dSYM/Contents/Info.plist" ]; then
    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $bundleVersion" "${BUILT_PRODUCTS_DIR}/${WRAPPER_NAME}.dSYM/Contents/Info.plist"
else
    echo "dSYM not found so bundle update not applied to that plist"
    echo "- ${BUILT_PRODUCTS_DIR}/${WRAPPER_NAME}.dSYM/Contents/Info.plist"
fi
```

Also possible the above script would fix the issue, as I think that's the main output from the archive - but I can't test that...

If you frankly don't care, just revert the script and I'll deal with the conflicts 😂

**Comment by rnystrom** [comment]
@Sherlouk I'm fine w/ that I think. We _shouldn't_ get conflicts b/c I'll be the only one pushing betas.

I'll give this a try!

**Comment by rnystrom** [comment]
Reverted
