### ISSUE TITLE
Rate limit handling

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#779]
Somehow I hit it. Need to maybe throttle or something.

![GitHawk Upload by Sherlouk](https://i.imgur.com/6R2NQ3D.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Need to calculate request scores. Looks like page size impacts the score of a request. We're using 100 for all sizes, we should try to tune these so we're not using so many resources.

https://developer.github.com/v4/guides/resource-limitations/

**Comment by Sherlouk** [comment]
There's a rateLimit attribute you can add to GraphQL requests. One of the values allows you to do dryRun as well but it'll tell you how many (exactly) tokens it needs to carry out the request. Maybe a question for the Apollo guys but if we could use [directives](http://graphql.org/learn/queries/#directives) we could pass through an argument which is "dryRun" which returns how many tokens. Then we can just check if the user has enough to carry it out?

Also yeah lets tone down some 100s!

**Comment by Sherlouk** [comment]
Okay so it looks like from a very quick bit of code, that every issue you open is 101 "tokens". You get 5000 tokens. That means if you open 49 issues, you'll exceed the limit. Obviously anything else that uses GQL (Like searching, loading repositories, loading repo contents, paging issues/prs, reacting to issues) is all using extra tokens.

I'm taking a look into what's causing the 101 more specifically, because that's a massive hitter! It might be worth adding the rateLimit clause to all queries and just printing it out so we can keep track of the big hitters!

```
rateLimit {
    cost
    remaining
    limit
    nodeCount
    resetAt
}
```
