### ISSUE TITLE
Bookmarks missing from latest TestFlight

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#823]
Some have disappeared - should test possible regressions like this in the future

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1137)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
All of mine have disappeared bit annoying, is this because they're now namespaced per-account? Likely had no migration.

I have (using FLEX) a "bookmarks" and a "com.whois.freetime.bookmarks" directory with a file within. Without looking at the code I assume the directory is the new one, with each file being an account. We could fairly easily just check for the "bookmarks" file and migrate it over? (or just tell people to deal with it 🤷‍♂️)

**Comment by rizwankce** [comment]
Namespaced bookmarks were in TF version 1127. Ideally, we should not get this missing bookmarks in TF 1137 🤔

**Comment by Sherlouk** [comment]
I don't think I used TF 1127 tbh, so moving straight to 1137 likely caused the issue. Bas said "some" have disappeared, the ones he had before 1127 would've been deleted and any new ones will have stayed?

A possibility anyway

**Comment by BasThomas** [comment]
Think the new ones are gone; not sure though.

**Comment by rizwankce** [comment]
@Sherlouk Yup. 

TF 1127 has this change for namespaced bookmarks. Previously all bookmarks saved under documents folder with directory named `Bookmarks`. Now with namespaced changes, we created a new directory `com.whois.freetime.bookmarks` and save each user bookmarks under file named by `user_token`

**Comment by rizwankce** [comment]
Maybe it is related to #822 
if you are missing bookmarks.

**Comment by Sherlouk** [comment]
I think since it is just on TF, we can deal with not having migration between the versions. Had it been on app store version I'd say the opposite

**Comment by rnystrom** [comment]
Yup they are flushed from the user namespace changes. Beta tester sacrifices 🙏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
