### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by MostafaAlaa2016** [rnystrom/GitHawk#989]
I make the notifications on and it didn’t push notifications to the mobile such as FB/Twitter

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.1 (1185)
Device: iPhone 8 Plus (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Hey @MostafaAlaa2016, notifications are not supported (yet). We do support badges though!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MostafaAlaa2016** [comment]
What’s the meaning of support badges?

**Comment by BasThomas** [comment]
The app icon will get the red dot indicating how many unread notifications you have. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MostafaAlaa2016** [comment]
Thanks, is there any plans to push notifications?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Push notifications have an open ticket (#224) - Unfortunately this would really require a server component to do active polling, otherwise I'm sure it'd be a top feature!

A simple/temporary compromise could be to use the background polling we already have and use `UILocalNotification` saying something like "You have x new notifications! Tap to read them!" or similar.

I'll move that suggestion to the linked issue to keep the discussion in one place!
